# Circle CI version
version: 2

## Customize the test machine
jobs:
  build:
    working_directory: ~/project
    # Set the timezone
    timezone: America/Mexico_City 

    # Env vars
    environment:
      - FOO: "bar"   

    docker:
        - image: circleci/node:8.11.2

    steps:
      - checkout
      - run:
          name: Aws
          command: sudo apt-get -y -qq install awscli

      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: install :/
          command: npm install

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-bower

      - run:
          name: install bower
          command: sudo npm i -g bower && which bower

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-bower
          paths:
            - /usr/local/lib/node_modules/bower
      
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-polymer

      - run:
          name: install polymer
          command: sudo npm i -g polymer-cli --unsafe-perm && which polymer
      
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-polymer
          paths:
            - /usr/local/lib/node_modules/polymer-cli

      - run:
          name: Polymer tesst
          command: |
            npm test

  # Deploy job          
  deploy:
    
    machine:
        enabled: true

    working_directory: ~/project

    steps:
      - checkout
      - run:
          name: Aws print version
          command: aws --version

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

