# Circle CI version
version: 2

## Customize the test machine
jobs:
  build: 
    # Set the timezone
    timezone: America/Mexico_City 

    # Env vars
    environment:
      - FOO: "bar"   

    docker:
        - image: circleci/node:8.11.2

    steps:
      # - run:
      #     name: pip
      #     command: if [ $CIRCLE_BRANCH = 'master' ]; then apt update && apt install awscli && apt install awsebcli, python-pip; fi
      # - run:
      #     name: upgrade
      #     command: if [ $CIRCLE_BRANCH = 'master' ]; then pip install --upgrade setuptools; fi
      # - run:
      #     name: install aws cli
      #     command: if [ $CIRCLE_BRANCH = 'master' ]; then pip install awsebcli; fi
      - run:
          name: upgrade
          working_directory: /
          command: |
            apt-get -y -qq update
            apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            pip install awscli --upgrade --user
      - run:
          name: install :/
          command: npm install
      - run:
          name: install bower
          command: npm i -g bower
      - run:
          name: install polymer
          command: npm i -g polymer-cli --unsafe-perm
      - run:
          name: Polymer tesst
          command: |
            npm test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

