# Circle CI version
version: 2

## Customize the test machine
jobs:
  build: 
    # Set the timezone
    timezone: America/Mexico_City 

    # Env vars
    environment:
      - FOO: "bar"   

    docker:
        - image: circleci/node:8.11.2

    steps:
      - run:
          name: upgrade
          command: if [ $CIRCLE_BRANCH = 'master' ]; then pip install --upgrade setuptools; fi
      - run:
          name: install aws cli
          command: if [ $CIRCLE_BRANCH = 'master' ]; then pip install awsebcli; fi
      - run:
          name: install :/
          command: npm install
      - run:
          name: install bower
          command: npm i -g bower
      - run:
          name: install polymer
          command: npm i -g polymer-cli --unsafe-perm
      - run:
          name: Polymer tesst
          command: |
            npm test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - build:
          requires:
            - build-job
          filters:
            branches:
              only: master

